export const INDUSTRY_OPTIONS = [
  "Sustainable Fashion",
  "Conscious Beauty",
  "Plant-Based Food",
  "Eco-Lifestyle",
  "Fashion & Apparel",
  "Beauty & Skincare",
  "Health & Fitness",
  "Food & Beverage",
  "Technology",
  "Travel & Hospitality",
  "Entertainment & Media",
  "Finance & Fintech",
  "Education",
  "Home & Lifestyle",
  "Automotive",
  "Other",
];

export const CREATOR_CATEGORIES = [
  "Sustainable Fashion",
  "Ethical Beauty",
  "Plant-Based Food",
  "Eco-Lifestyle",
  "Zero Waste",
  "Fashion",
  "Beauty",
  "Fitness",
  "Food",
  "Travel",
  "Tech",
  "Lifestyle",
  "Parenting",
  "Gaming",
  "Finance",
];
